- type: job
  id: Captain
  name: job-name-captain
  description: job-description-captain
  playTimeTracker: JobCaptain
  requirements:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 10h # LP edit
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 10h # LP edit
    - !type:DepartmentTimeRequirement
      department: Science
      time: 10h # LP edit
    - !type:DepartmentTimeRequirement
      department: Security
      time: 10h # LP edit
#    - !type:DepartmentTimeRequirement
#      department: Command
#      time: 4h
    - !type:OverallPlaytimeRequirement
      time: 50h # LP edit
    - !type:TraitsRequirement #Corvax-TraitsRequirement
      inverted: true
      traits:
      - Muted
    #LP edit start
    - !type:AgeRequirement
      requiredAge: 26
    #LP edit end
  weight: 20
  startingGear: CaptainGear
  icon: "JobIconCaptain"
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  - Cargo # LP Edit
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: CaptainGear
  equipment:
    shoes: ClothingShoesBootsLaceup
    eyes: ClothingEyesGlassesCommand
    gloves: ClothingHandsGlovesCaptain
    id: CaptainPDA
    ears: ClothingHeadsetAltCommand
  storage:
    back:
    - Flash
    # - StationCharter

- type: chameleonOutfit
  id: CaptainChameleonOutfit
  job: Captain
  hasMindShield: true
  equipment:
    head: ClothingHeadHatCapcap
    eyes: ClothingEyesGlassesCommand
    mask: ClothingMaskGasCaptain
    neck: ClothingNeckCloakCap
