# Модули для боргов
- type: latheRecipePack
  id: LPPSecurityModuls
  recipes:
  - LPPBorgModuleSecurityWeapon
  - LPPBorgModuleSecurityLaserCarbine
  - LPPBorgModuleSecurityCriminologist

- type: latheRecipePack
  id: LPPSpaceForgeCMDHardsuits
  recipes:
  - LPPClothingHeadHelmetEVALarge
  - LPPClothingOuterHardsuitEVAPrisoner
  - LPPClothingOuterHardsuitCombatOfficer
  - LPPClothingOuterHardsuitSecurity
  - LPPClothingOuterHardsuitCombatMedical
  - LPPClothingOuterHardsuitCombatRiot
  - LPPClothingOuterHardsuitSecurityPilot
  - LPPClothingOuterHardsuitSecurityEng
  - LPPClothingOuterHardsuitBrigmedic
  - LPPClothingOuterHardsuitWarden
  - LPPClothingOuterHardsuitLuxury
  - LPPClothingOuterHardsuitRd
  - LPPClothingOuterHardsuitMedical
  - LPPClothingOuterHardsuitEngineeringWhite
  - LPPClothingOuterHardsuitSecurityRed
  - LPPClothingOuterHardsuitCap

- type: latheRecipePack
  id: LPPGrenadeLauncherSec
  recipes:
  - LPPWeaponLauncherHydrozoa
  - LPPGrenadeBaton
  - LPPGrenadeEMP
