using Content.Client.Parallax;
using Content.Client.Research;
using Content.Client.UserInterface.Controls;
using Content.Shared._NF.Research;
using Content.Shared.Access.Systems;
using Content.Shared.Research.Components;
using Content.Shared.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using System.Numerics;
// LP edit start
using System.Collections.Generic;
using System.Linq;
// LP edit end

namespace Content.Client._NF.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class FancyResearchConsoleMenu : FancyWindow
{
    public Action<string>? OnTechnologyCardPressed;
    public Action? OnServerButtonPressed;

    [Dependency] private readonly IEntityManager _entity = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly IPlayerManager _player = default!;

    private readonly ResearchSystem _research;
    private readonly SpriteSystem _sprite;
    private readonly AccessReaderSystem _accessReader;
    private ParallaxControl _parallaxControl;

    /// <summary>
    /// The parallax prototype to use for the background. Configurable.
    /// </summary>
    public string ParallaxPrototype { get; set; } = "Default";

    /// <summary>
    /// Updates the parallax background to use a different prototype
    /// </summary>
    /// <param name="parallaxPrototype">The new parallax prototype to use</param>
    public void SetParallaxPrototype(string parallaxPrototype)
    {
        ParallaxPrototype = parallaxPrototype;
        if (_parallaxControl != null)
        {
            _parallaxControl.ParallaxPrototype = parallaxPrototype;
        }
    }

    /// <summary>
    /// Console entity
    /// </summary>
    public EntityUid Entity;

    /// <summary>
    /// Currently selected tech
    /// Exists for better UI refreshing
    /// </summary>
    public ProtoId<TechnologyPrototype>? CurrentTech;

    /// <summary>
    /// All technologies and their availability
    /// </summary>
    public Dictionary<string, ResearchAvailability> List = new();

    /// <summary>
    /// Cached research points
    /// </summary>
    public int Points = 0;

    /// <summary>
    /// Is tech currently being dragged
    /// </summary>
    private bool _draggin;

    /// <summary>
    /// Current discipline filter. If null, all disciplines are shown.
    /// </summary>
    private string? _currentDisciplineFilter; // LP edit

    /// <summary>
    /// the distance between elements on the grid.
    /// </summary>
    private const int GridSize = 90;

    /// <summary>
    /// technology cards size.
    /// </summary>
    private const int CardSize = 64;

    /// <summary>
    /// the origin point of the grid.
    /// </summary>
    private static readonly Vector2i DefaultPosition = Vector2i.Zero;

    private Box2i _bounds = new(DefaultPosition, DefaultPosition);

    private const string DisciplineIndustrial = "Industrial";
    private const string DisciplineArsenal = "Arsenal";
    private const string DisciplineExperimental = "Experimental";
    private const string DisciplineCivilianServices = "CivilianServices";

    public FancyResearchConsoleMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _research = _entity.System<ResearchSystem>();
        _sprite = _entity.System<SpriteSystem>();
        _accessReader = _entity.System<AccessReaderSystem>();

        // Set up scroll container properties
        TechScrollContainer.ScrollSpeedX = 100;
        TechScrollContainer.ScrollSpeedY = 100;
        TechScrollContainer.HScrollEnabled = true; // LP edit
        TechScrollContainer.VScrollEnabled = true;

        // Frontier: Initialize parallax background
        _parallaxControl = new ParallaxControl
        {
            ParallaxPrototype = ParallaxPrototype,
            HorizontalExpand = true,
            VerticalExpand = true,
        };

        // Add the parallax control to the ResearchesContainer at the beginning (bottom layer)
        ResearchesContainer.AddChild(_parallaxControl);

        // Set the proper rendering order by adjusting positions in the parent's child list
        // Controls with a higher position value are drawn on top (foreground)
        // Make sure the parallax is at the bottom of the z-order (drawn first)
        _parallaxControl.SetPositionInParent(0);

        // The drag container should be in the middle
        TechScrollContainer.SetPositionInParent(1);

        // Apply scrollbar styling
        ApplyScrollbarStyling();

        // Set up event handlers
        ServerButton.OnPressed += _ => OnServerButtonPressed?.Invoke();
        DragContainer.OnKeyBindDown += OnKeybindDown;
        DragContainer.OnKeyBindUp += OnKeybindUp;
        RecenterButton.OnPressed += _ => Recenter();

        // LP edit start
        // Search functionality
        SearchBar.OnTextChanged += _ => UpdateSearchResults(SearchBar.Text);
        SearchBar.OnFocusEnter += _ => _draggin = false;
        SearchBar.OnKeyBindDown += OnSearchBarKeyDown;
        // ItemList doesn't have OnFocusEnter, use MouseFilter or OnItemSelected instead
        SearchResultsList.OnItemSelected += args => OnTechnologySelected(args);

        // Discipline filter buttons
        FilterAllButton.OnPressed += _ => SetDisciplineFilter(null);
        FilterIndustrialButton.OnPressed += _ => SetDisciplineFilter(DisciplineIndustrial);
        FilterArsenalButton.OnPressed += _ => SetDisciplineFilter(DisciplineArsenal);
        FilterExperimentalButton.OnPressed += _ => SetDisciplineFilter(DisciplineExperimental);
        FilterCivilianButton.OnPressed += _ => SetDisciplineFilter(DisciplineCivilianServices);

        // Load discipline icons
        var industrial = _prototype.Index<TechDisciplinePrototype>(DisciplineIndustrial);
        var arsenal = _prototype.Index<TechDisciplinePrototype>(DisciplineArsenal);
        var experimental = _prototype.Index<TechDisciplinePrototype>(DisciplineExperimental);
        var civilian = _prototype.Index<TechDisciplinePrototype>(DisciplineCivilianServices);

        FilterIndustrialIcon.Texture = _sprite.Frame0(industrial.Icon);
        FilterArsenalIcon.Texture = _sprite.Frame0(arsenal.Icon);
        FilterExperimentalIcon.Texture = _sprite.Frame0(experimental.Icon);
        FilterCivilianIcon.Texture = _sprite.Frame0(civilian.Icon);
        // LP edit end

        // Empty initialization
        UpdatePanels(List);
    }

    /// <summary>
    /// Apply scrollbar styling using centralized colors and utilities
    /// </summary>
    private void ApplyScrollbarStyling()
    {
        var scrollBarNormal = ResearchUIHelpers.CreateScrollbarStyleBox("normal");
        var scrollBarHovered = ResearchUIHelpers.CreateScrollbarStyleBox("hovered");
        var scrollBarGrabbed = ResearchUIHelpers.CreateScrollbarStyleBox("grabbed");
    }

    public void SetEntity(EntityUid entity)
        => Entity = entity;

    public void UpdatePanels(Dictionary<string, ResearchAvailability> dict)
    {
        // Clear existing items
        DragContainer.RemoveAllChildren();

        List = dict;
        var bounds = new Box2i();
        var boundsSet = false;

        // Calculate bounds
        foreach (var tech in List)
        {
            var proto = _prototype.Index<TechnologyPrototype>(tech.Key);

            // LP Edit Start
            if (proto.Hidden)
                continue;
            // LP Edit End

            var position = DefaultPosition + (GridSize * proto.Position.X, GridSize * proto.Position.Y);

            if (!boundsSet)
            {
                bounds.BottomLeft = position;
                bounds.TopRight = position;
                boundsSet = true;
            }
            else
            {
                bounds.Left = int.Min(position.X, bounds.Left);
                bounds.Bottom = int.Min(position.Y, bounds.Bottom);
                bounds.Right = int.Max(position.X, bounds.Right);
                bounds.Top = int.Max(position.Y, bounds.Top);
            }
        }

        if (boundsSet)
        {
            _bounds = bounds;

            // Set container size with padding
            var padding = 200;
            var totalWidth = _bounds.Width + CardSize + padding;
            var totalHeight = _bounds.Height + CardSize + padding;

            DragContainer.SetWidth = Math.Max(totalWidth, 1000);
            DragContainer.SetHeight = Math.Max(totalHeight, 1000);
        }

        // Add tech items
        foreach (var tech in List)
        {
            var proto = _prototype.Index<TechnologyPrototype>(tech.Key);

            // LP Edit Start
            if (proto.Hidden)
                continue;
            // LP Edit End

            var control = new FancyResearchConsoleItem(proto, _sprite, tech.Value);

            DragContainer.AddChild(control);

            // Position the tech item
            var leftPadding = 20;
            var topPadding = 20;
            var uiPosition = new Vector2(
                proto.Position.X * GridSize - _bounds.Left + leftPadding,
                proto.Position.Y * GridSize - _bounds.Bottom + topPadding
            );

            LayoutContainer.SetPosition(control, uiPosition);
            control.SelectAction += SelectTech;
            control.IsSelected = tech.Key == CurrentTech;
        }

        UpdateSearchResults(SearchBar.Text); // LP edit
    }

    public void UpdateInformationPanel(int points)
    {
        Points = points;

        var amountMsg = new FormattedMessage();
        amountMsg.AddMarkupOrThrow(Loc.GetString("research-console-menu-research-points-text",
            ("points", points)));
        ResearchAmountLabel.SetMessage(amountMsg);

        if (!_entity.TryGetComponent(Entity, out TechnologyDatabaseComponent? database))
            return;

        TierDisplayContainer.RemoveAllChildren();
        foreach (var disciplineId in database.SupportedDisciplines)
        {
            var discipline = _prototype.Index<TechDisciplinePrototype>(disciplineId);
            var tier = _research.GetTierCompletionPercentage(database, discipline, _prototype);

            // LP edit start
            switch (disciplineId)
            {
                case DisciplineIndustrial:
                    FilterIndustrialPercent.SetMessage(Loc.GetString("research-console-tier-percentage", ("perc", tier)));
                    break;
                case DisciplineArsenal:
                    FilterArsenalPercent.SetMessage(Loc.GetString("research-console-tier-percentage", ("perc", tier)));
                    break;
                case DisciplineExperimental:
                    FilterExperimentalPercent.SetMessage(Loc.GetString("research-console-tier-percentage", ("perc", tier)));
                    break;
                case DisciplineCivilianServices:
                    FilterCivilianPercent.SetMessage(Loc.GetString("research-console-tier-percentage", ("perc", tier)));
                    break;
            }
            // LP edit end
        }
    }

    #region Drag handle
    protected override void MouseMove(GUIMouseMoveEventArgs args)
    {
        base.MouseMove(args);

        if (!_draggin)
            return;

        // Adjust scroll position with drag (both vertical and horizontal) // LP edit
        var scrollSpeed = 2.0f;
        TechScrollContainer.VScrollTarget -= args.Relative.Y * scrollSpeed;
        TechScrollContainer.HScrollTarget -= args.Relative.X * scrollSpeed; // LP edit
    }

    /// <summary>
    /// Raised when LMB is pressed at <see cref="DragContainer"/>
    /// </summary>
    private void OnKeybindDown(GUIBoundKeyEventArgs args)
    {
        if (args.Function == EngineKeyFunctions.Use)
            _draggin = true;
    }

    /// <summary>
    /// Raised when LMB is unpressed at <see cref="DragContainer"/>
    /// </summary>
    private void OnKeybindUp(GUIBoundKeyEventArgs args)
    {
        if (args.Function == EngineKeyFunctions.Use)
            _draggin = false;
    }

    protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
        => _draggin ? DragMode.None : base.GetDragModeFor(relativeMousePos);
    #endregion

    /// <summary>
    /// Selects a tech prototype and opens info panel
    /// </summary>
    /// <param name="proto">Tech proto</param>
    /// <param name="availability">Tech availability</param>
    public void SelectTech(TechnologyPrototype proto, ResearchAvailability availability)
    {
        InfoContainer.RemoveAllChildren();
        if (!_player.LocalEntity.HasValue)
            return;

        // Update selection
        CurrentTech = proto.ID;

        // Update visual selection state
        foreach (var child in DragContainer.Children)
        {
            if (child is FancyResearchConsoleItem techItem)
            {
                techItem.IsSelected = techItem.Prototype.ID == CurrentTech;
            }
        }

        // Create and add info panel
        var control = new FancyTechnologyInfoPanel(proto, _accessReader.IsAllowed(_player.LocalEntity.Value, Entity), availability, _sprite);
        control.BuyAction += args => OnTechnologyCardPressed?.Invoke(args.ID);
        InfoContainer.AddChild(control);
    }

    // LP edit start
    /// <summary>
    /// Updates the search results dropdown based on the search query
    /// </summary>
    private void UpdateSearchResults(string filter)
    {
        SearchResultsList.Clear();

        if (string.IsNullOrWhiteSpace(filter))
        {
            SearchResultsList.Visible = false;
            foreach (var child in DragContainer.Children)
            {
                if (child is FancyResearchConsoleItem techItem)
                {
                    techItem.Visible = _currentDisciplineFilter == null || techItem.Prototype.Discipline == _currentDisciplineFilter;
                }
            }
            return;
        }

        var lowerFilter = filter.Trim().ToLowerInvariant();
        var matches = new List<TechnologyPrototype>();

        foreach (var tech in List)
        {
            var proto = _prototype.Index<TechnologyPrototype>(tech.Key);
            var techName = Loc.GetString(proto.Name).ToLowerInvariant();

            // Apply both search filter and discipline filter
            var matchesSearch = techName.Contains(lowerFilter);
            var matchesDiscipline = _currentDisciplineFilter == null || proto.Discipline == _currentDisciplineFilter;

            if (matchesSearch && matchesDiscipline)
            {
                matches.Add(proto);
            }
        }

        foreach (var tech in matches)
        {
            SearchResultsList.Add(new ItemList.Item(SearchResultsList)
            {
                Metadata = tech,
                Text = Loc.GetString(tech.Name),
                Icon = _sprite.Frame0(tech.Icon)
            });
        }

        SearchResultsList.Visible = SearchResultsList.Count > 0;

        foreach (var child in DragContainer.Children)
        {
            if (child is FancyResearchConsoleItem techItem)
            {
                techItem.Visible = matches.Any(t => t.ID == techItem.Prototype.ID);
            }
        }
    }

    /// <summary>
    /// Handles technology selection from the search results dropdown
    /// </summary>
    private void OnTechnologySelected(ItemList.ItemListSelectedEventArgs args)
    {
        _draggin = false;

        var selectedTech = args.ItemList[args.ItemIndex].Metadata as TechnologyPrototype;
        if (selectedTech != null)
        {
            foreach (var child in DragContainer.Children)
            {
                if (child is FancyResearchConsoleItem techItem && techItem.Prototype.ID == selectedTech.ID)
                {
                    SelectTech(selectedTech, List[selectedTech.ID]);

                    var techPosition = GetTechnologyPosition(selectedTech);
                    TechScrollContainer.VScrollTarget = techPosition.Y - 100; // Add some padding
                    TechScrollContainer.HScrollTarget = techPosition.X - 100;

                    break;
                }
            }

        }
    }

    /// <summary>
    /// Sets the discipline filter and updates the displayed technologies
    /// </summary>
    private void SetDisciplineFilter(string? discipline)
    {
        _currentDisciplineFilter = discipline;
        UpdateSearchResults(SearchBar.Text);

        // Update button visual states to indicate which filter is active
        FilterAllButton.Pressed = discipline == null;
        FilterIndustrialButton.Pressed = discipline == DisciplineIndustrial;
        FilterArsenalButton.Pressed = discipline == DisciplineArsenal;
        FilterExperimentalButton.Pressed = discipline == DisciplineExperimental;
        FilterCivilianButton.Pressed = discipline == DisciplineCivilianServices;
    }

    /// <summary>
    /// Handles key presses in the search bar
    /// </summary>
    private void OnSearchBarKeyDown(GUIBoundKeyEventArgs args)
    {
        if (args.Function == EngineKeyFunctions.TextSubmit)
        {
            // If Enter key is pressed and there's at least one search result, select the first one
            if (SearchResultsList.Count > 0)
            {
                OnTechnologySelected(new ItemList.ItemListSelectedEventArgs(0, SearchResultsList));
            }
        }
        else if (args.Function == EngineKeyFunctions.CloseModals || args.Function == EngineKeyFunctions.EscapeMenu)
        {
            SearchBar.Text = "";
            SearchResultsList.Visible = false;
        }
    }

    /// <summary>
    /// Gets the screen position of a technology item in the scroll container
    /// </summary>
    private Vector2 GetTechnologyPosition(TechnologyPrototype proto)
    {
        var leftPadding = 20;
        var topPadding = 20;
        var uiPosition = new Vector2(
            proto.Position.X * GridSize - _bounds.Left + leftPadding,
            proto.Position.Y * GridSize - _bounds.Bottom + topPadding
        );
        return uiPosition;
    }
    // LP edit end

    public void Recenter()
    {
        // Reset scroll position
        TechScrollContainer.VScrollTarget = 0;
        TechScrollContainer.HScrollTarget = 0; // LP edit
    }

    public override void Close()
    {
        base.Close();
        DragContainer.RemoveAllChildren();
        InfoContainer.RemoveAllChildren();
    }

    private sealed partial class DisciplineButton(TechDisciplinePrototype proto) : Button
    {
        public TechDisciplinePrototype Proto = proto;
    }

    protected override void MouseWheel(GUIMouseWheelEventArgs args)
    {
        base.MouseWheel(args);
    }
}
