- type: entity
  id: LPPNTRCrateToolsExperimental
  parent: CrateEngineeringSecure
  name: experimental tools supply
  description: Experimental tools are extremely practical, aren't they?
  components:
  - type: StorageFill
    contents:
      - id: JawsOfLife
      - id: PowerDrill
      - id: WelderExperimental
      - id: RCDExperimental
      - id: RPDExperimental

- type: entity
  parent: BoxEncryptionKeyPassenger
  id: LPPBoxEncryptionKeyCentcomm
  name: centcomm encryption key box
  components:
  - type: EntityTableContainerFill
    containers:
      storagebase:
        id: EncryptionKeyCentCom
        amount: 4

- type: entity
  id: LPPNTRCrateClothingOuterArmorBasic
  parent: CrateLockBoxSecurity
  name: outer armor basic supply
  description: Conventional body armor, most often issued to Nanotrain trainees.
  components:
  - type: StorageFill
    contents:
      - id: ClothingOuterArmorBasic
        amount: 3

- type: entity
  id: LPPBlueshieldUndeterminedWeapon
  name: blueshield sets pack
  description: A small box utilizing bluespace technology to drop in a loadout directly to you. Choose wisely.
  parent: [ BaseItem, BaseSetSelector, BaseCentcommContraband ]
  components:
  - type: Sprite
    sprite: _GoobStation/Objects/Specific/Security/blueshieldundetermined.rsi
    state: icon
  - type: SetSelector
    possibleSets:
    - BSOBlueshieldSet
    - BSORevolverSet
    - BSOChesterSet
    - BSOSyringeSet
    - LPPBSOCFrenchSet
    maxSelectedSets: 1
